services:
  crm-receiver:
    build: .
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  crm-heartbeat:
    build: .
    command: node src/heartbeat.js
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
